#!/bin/bash
# setup_nextcloud_client.sh - Setup Nextcloud client automation
#
# This script:
# 1. Installs Nextcloud desktop client or CLI tools
# 2. Configures sync folders
# 3. Sets up automatic synchronization (systemd timer)

set -euo pipefail

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load common functions
source "${SCRIPT_DIR}/common.sh"

# Check root privileges
check_root

# =============================================================================
# MAIN FUNCTIONS
# =============================================================================

# Install Nextcloud client
install_nextcloud_client() {
    log_info "Installing Nextcloud client..."
    
    # Try to install nextcloud-desktop first (GUI client with CLI)
    if apt-cache show nextcloud-desktop >/dev/null 2>&1; then
        install_package nextcloud-desktop
        log_info "Nextcloud desktop client installed"
        return 0
    fi
    
    # Fallback to nextcloudcmd (command-line only)
    if apt-cache show nextcloud-client-cmd >/dev/null 2>&1; then
        install_package nextcloud-client-cmd
        log_info "Nextcloud command-line client installed"
        return 0
    fi
    
    # If neither is available, add PPA
    log_info "Adding Nextcloud PPA repository..."
    install_package software-properties-common
    
    add-apt-repository -y ppa:nextcloud-devs/client || {
        log_warning "Failed to add PPA, trying snap installation..."
        install_nextcloud_snap
        return $?
    }
    
    apt-get update -qq
    install_package nextcloud-client-cmd
    
    log_info "Nextcloud client installed successfully"
}

# Install Nextcloud via snap (alternative method)
install_nextcloud_snap() {
    log_info "Installing Nextcloud client via snap..."
    
    if ! command_exists snap; then
        install_package snapd
        systemctl enable --now snapd
        sleep 2
    fi
    
    snap install nextcloud-client || die "Failed to install Nextcloud via snap"
    
    log_info "Nextcloud client installed via snap"
}

# Create sync script
create_sync_script() {
    local sync_script="/usr/local/bin/nextcloud-sync.sh"
    local server_url="${NEXTCLOUD_SERVER_URL:?Nextcloud server URL not configured}"
    local username="${NEXTCLOUD_USER:?Nextcloud username not configured}"
    local password="${NEXTCLOUD_PASSWORD:?Nextcloud password not configured}"
    local local_dir="${NEXTCLOUD_LOCAL_DIR:?Nextcloud local directory not configured}"
    local remote_dir="${NEXTCLOUD_REMOTE_DIR:-/}"
    
    log_info "Creating Nextcloud sync script..."
    
    # Ensure local directory exists
    ensure_directory "$local_dir" "root:root" "0755"
    
    # Create sync script
    cat > "$sync_script" <<'EOF'
#!/bin/bash
# Nextcloud sync script
# Auto-generated by setup_nextcloud_client.sh

# Load configuration
CONFIG_FILE="${CONFIG_FILE:-/etc/dk-b-server.conf}"
if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
fi

# Configuration
SERVER_URL="${NEXTCLOUD_SERVER_URL}"
USERNAME="${NEXTCLOUD_USER}"
PASSWORD="${NEXTCLOUD_PASSWORD}"
LOCAL_DIR="${NEXTCLOUD_LOCAL_DIR}"
REMOTE_DIR="${NEXTCLOUD_REMOTE_DIR:-/}"
LOG_DIR="${LOG_DIR:-/var/log/dk-b-server}"
LOG_FILE="${LOG_DIR}/nextcloud-sync.log"

# Ensure log directory exists
mkdir -p "$LOG_DIR"

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

log "Starting Nextcloud sync..."

# Check if nextcloudcmd is available
if ! command -v nextcloudcmd >/dev/null 2>&1; then
    log "ERROR: nextcloudcmd not found"
    exit 1
fi

# Check if local directory exists
if [ ! -d "$LOCAL_DIR" ]; then
    log "Creating local directory: $LOCAL_DIR"
    mkdir -p "$LOCAL_DIR"
fi

# Perform sync
log "Syncing: $LOCAL_DIR <-> $SERVER_URL$REMOTE_DIR"

# Run nextcloudcmd with credentials
if nextcloudcmd \
    --user "$USERNAME" \
    --password "$PASSWORD" \
    --non-interactive \
    --silent \
    "$LOCAL_DIR" \
    "$SERVER_URL$REMOTE_DIR" >> "$LOG_FILE" 2>&1; then
    log "Sync completed successfully"
    exit 0
else
    log "ERROR: Sync failed with exit code $?"
    exit 1
fi
EOF
    
    # Make script executable
    chmod +x "$sync_script"
    
    log_info "Sync script created: $sync_script"
}

# Create systemd service
create_systemd_service() {
    local service_file="/etc/systemd/system/nextcloud-sync.service"
    
    log_info "Creating systemd service..."
    
    cat > "$service_file" <<EOF
[Unit]
Description=Nextcloud Sync Service
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/nextcloud-sync.sh
User=root
Group=root
StandardOutput=journal
StandardError=journal
Environment="CONFIG_FILE=/etc/dk-b-server.conf"

# Security settings
PrivateTmp=yes
NoNewPrivileges=yes

[Install]
WantedBy=multi-user.target
EOF
    
    log_info "Systemd service created"
}

# Create systemd timer
create_systemd_timer() {
    local timer_file="/etc/systemd/system/nextcloud-sync.timer"
    local sync_interval="${NEXTCLOUD_SYNC_INTERVAL:-5}"
    
    log_info "Creating systemd timer (interval: ${sync_interval} minutes)..."
    
    cat > "$timer_file" <<EOF
[Unit]
Description=Nextcloud Sync Timer
Requires=nextcloud-sync.service

[Timer]
# Run every ${sync_interval} minutes
OnBootSec=2min
OnUnitActiveSec=${sync_interval}min
AccuracySec=1min

[Install]
WantedBy=timers.target
EOF
    
    log_info "Systemd timer created"
}

# Enable and start systemd timer
enable_sync_timer() {
    log_info "Enabling Nextcloud sync timer..."
    
    # Reload systemd
    systemctl daemon-reload
    
    # Enable and start timer
    systemctl enable nextcloud-sync.timer || log_warning "Failed to enable timer"
    systemctl start nextcloud-sync.timer || die "Failed to start timer"
    
    # Check timer status
    if systemctl is-active --quiet nextcloud-sync.timer; then
        log_info "Nextcloud sync timer is active"
    else
        die "Nextcloud sync timer failed to start"
    fi
    
    # Show timer status
    log_info "Timer status:"
    systemctl status nextcloud-sync.timer --no-pager | head -n 20 | while read -r line; do
        log_info "  $line"
    done
    
    # Show timer schedule
    log_info ""
    log_info "Next sync times:"
    systemctl list-timers nextcloud-sync.timer --no-pager | while read -r line; do
        log_info "  $line"
    done
}

# Test sync
test_sync() {
    log_info "Testing Nextcloud sync..."
    
    # Run sync manually
    if /usr/local/bin/nextcloud-sync.sh; then
        log_info "Test sync completed successfully"
    else
        log_warning "Test sync failed - check credentials and server configuration"
        log_warning "Review logs at: ${LOG_DIR}/nextcloud-sync.log"
        return 1
    fi
}

# Create credential file (alternative secure method)
create_netrc_file() {
    local netrc_file="/root/.netrc"
    local server_url="${NEXTCLOUD_SERVER_URL}"
    local username="${NEXTCLOUD_USER}"
    local password="${NEXTCLOUD_PASSWORD}"
    
    log_info "Creating .netrc file for authentication..."
    
    # Extract hostname from URL
    local hostname=$(echo "$server_url" | sed -e 's|^[^/]*//||' -e 's|/.*$||')
    
    # Create or update .netrc
    if [ -f "$netrc_file" ]; then
        backup_file "$netrc_file"
    fi
    
    cat > "$netrc_file" <<EOF
machine $hostname
login $username
password $password
EOF
    
    # Secure permissions
    chmod 600 "$netrc_file"
    
    log_info ".netrc file created"
}

# Show sync status
show_sync_status() {
    log_info "Nextcloud Sync Status:"
    log_info "----------------------------------------"
    
    # Service status
    log_info "Service:"
    if systemctl is-active --quiet nextcloud-sync.service; then
        log_info "  Status: Active (syncing now)"
    else
        log_info "  Status: Inactive"
    fi
    
    # Timer status
    log_info ""
    log_info "Timer:"
    if systemctl is-active --quiet nextcloud-sync.timer; then
        log_info "  Status: Active"
        
        # Show next run time
        local next_run=$(systemctl status nextcloud-sync.timer | grep "Trigger:" | sed 's/.*Trigger: //')
        if [ -n "$next_run" ]; then
            log_info "  Next sync: $next_run"
        fi
    else
        log_info "  Status: Inactive"
    fi
    
    # Recent logs
    log_info ""
    log_info "Recent sync log entries:"
    if [ -f "${LOG_DIR}/nextcloud-sync.log" ]; then
        tail -n 5 "${LOG_DIR}/nextcloud-sync.log" | while read -r line; do
            log_info "  $line"
        done
    else
        log_info "  No logs yet"
    fi
    
    log_info "----------------------------------------"
}

# =============================================================================
# MAIN EXECUTION
# =============================================================================

main() {
    log_info "Starting Nextcloud client setup..."
    
    # Check if Nextcloud is enabled
    if [ "${ENABLE_NEXTCLOUD:-no}" != "yes" ]; then
        log_info "Nextcloud client is disabled in configuration"
        return 0
    fi
    
    # Acquire lock
    acquire_lock
    
    # Install Nextcloud client
    install_nextcloud_client
    
    # Create sync script
    create_sync_script
    
    # Create systemd units
    create_systemd_service
    create_systemd_timer
    
    # Enable sync timer
    enable_sync_timer
    
    # Create .netrc for authentication
    create_netrc_file
    
    # Test sync
    if ! test_sync; then
        log_warning "Initial sync test failed"
        log_warning "Please verify configuration and check logs"
    fi
    
    # Show status
    show_sync_status
    
    log_info "Nextcloud client setup completed successfully"
    log_info ""
    log_info "Sync configuration:"
    log_info "  Server: ${NEXTCLOUD_SERVER_URL}"
    log_info "  Local directory: ${NEXTCLOUD_LOCAL_DIR}"
    log_info "  Sync interval: ${NEXTCLOUD_SYNC_INTERVAL:-5} minutes"
    log_info "  Log file: ${LOG_DIR}/nextcloud-sync.log"
    
    return 0
}

# Run main function
main "$@"
