#!/bin/bash
# setup_samba_nfs.sh - Configure Samba and NFS file sharing
#
# This script:
# 1. Installs Samba and NFS server packages
# 2. Configures Samba share for iSCSI storage
# 3. Configures NFS export for iSCSI storage
# 4. Starts and enables services

set -euo pipefail

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load common functions
source "${SCRIPT_DIR}/common.sh"

# Check root privileges
check_root

# =============================================================================
# SAMBA FUNCTIONS
# =============================================================================

# Install Samba
install_samba() {
    log_info "Installing Samba..."
    
    install_package samba
    install_package samba-common-bin
    
    log_info "Samba installed successfully"
}

# Configure Samba
configure_samba() {
    local share_name="${SAMBA_SHARE_NAME:-iscsi-storage}"
    local share_path="${SAMBA_SHARE_PATH:-${ISCSI_MOUNT_POINT}}"
    local workgroup="${SAMBA_WORKGROUP:-WORKGROUP}"
    local guest_ok="${SAMBA_GUEST_OK:-yes}"
    local read_only="${SAMBA_READ_ONLY:-no}"
    local smb_conf="/etc/samba/smb.conf"
    
    log_info "Configuring Samba..."
    
    # Backup original config
    backup_file "$smb_conf"
    
    # Create new configuration
    cat > "$smb_conf" <<EOF
# Samba configuration for DK-B-Server
# Generated by setup_samba_nfs.sh

[global]
    workgroup = $workgroup
    server string = DK-B-Server Samba Server
    security = user
    map to guest = bad user
    log file = /var/log/samba/%m.log
    max log size = 50
    
    # Performance optimization
    socket options = TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=524288 SO_SNDBUF=524288
    read raw = yes
    write raw = yes
    max xmit = 65535
    aio read size = 16384
    aio write size = 16384
    
    # Modern SMB protocol support
    server min protocol = SMB2
    server max protocol = SMB3
    
    # DNS and WINS
    dns proxy = no
    
    # Printing disabled
    load printers = no
    printing = bsd
    printcap name = /dev/null
    disable spoolss = yes

[$share_name]
    comment = iSCSI Storage Share
    path = $share_path
    browseable = yes
    read only = $read_only
    guest ok = $guest_ok
    create mask = 0644
    directory mask = 0755
    force user = root
    force group = root
    
    # Performance optimizations
    strict allocate = yes
    allocation roundup size = 4096
    
    # VFS modules for better performance
    vfs objects = acl_xattr catia fruit streams_xattr
    
    # macOS support
    fruit:metadata = stream
    fruit:model = MacSamba
    fruit:veto_appledouble = no
    fruit:posix_rename = yes
    fruit:zero_file_id = yes
    fruit:wipe_intentionally_left_blank_rfork = yes
    fruit:delete_empty_adfiles = yes
EOF
    
    log_info "Samba configuration created"
    
    # Test configuration
    if testparm -s "$smb_conf" >/dev/null 2>&1; then
        log_info "Samba configuration is valid"
    else
        log_error "Samba configuration has errors"
        testparm -s "$smb_conf"
        return 1
    fi
    
    # Ensure share path exists
    ensure_directory "$share_path" "root:root" "0755"
}

# Start Samba services
start_samba() {
    log_info "Starting Samba services..."
    
    # Stop services first to ensure clean start
    systemctl stop smbd nmbd 2>/dev/null || true
    
    # Enable and start services
    enable_and_start_service smbd
    enable_and_start_service nmbd
    
    log_info "Samba services started successfully"
}

# =============================================================================
# NFS FUNCTIONS
# =============================================================================

# Install NFS server
install_nfs() {
    log_info "Installing NFS server..."
    
    install_package nfs-kernel-server
    install_package nfs-common
    
    log_info "NFS server installed successfully"
}

# Configure NFS exports
configure_nfs() {
    local export_path="${NFS_EXPORT_PATH:-${ISCSI_MOUNT_POINT}}"
    local allowed_networks="${NFS_ALLOWED_NETWORKS:-192.168.1.0/24}"
    local nfs_options="${NFS_OPTIONS:-rw,sync,no_subtree_check,no_root_squash}"
    local exports_file="/etc/exports"
    
    log_info "Configuring NFS exports..."
    
    # Backup original exports
    backup_file "$exports_file"
    
    # Ensure export path exists
    ensure_directory "$export_path" "root:root" "0755"
    
    # Check if export already exists
    if grep -q "^${export_path}" "$exports_file" 2>/dev/null; then
        log_info "Export for $export_path already exists, updating..."
        sed -i "\|^${export_path}|d" "$exports_file"
    fi
    
    # Add export entries for each allowed network
    log_info "Adding NFS export: $export_path"
    for network in $allowed_networks; do
        echo "$export_path $network($nfs_options)" >> "$exports_file"
        log_info "  Network: $network with options: $nfs_options"
    done
    
    log_info "NFS exports configured"
    
    # Validate exports file
    if exportfs -a 2>&1 | grep -q "error"; then
        log_error "NFS exports configuration has errors"
        return 1
    fi
}

# Configure NFS server settings
configure_nfs_server() {
    local nfs_conf="/etc/nfs.conf"
    
    log_info "Configuring NFS server settings..."
    
    # Backup original config
    backup_file "$nfs_conf"
    
    # Optimize NFS server settings
    cat >> "$nfs_conf" <<EOF

# DK-B-Server NFS optimizations
[nfsd]
threads = 8
vers2 = n
vers3 = y
vers4 = y
vers4.0 = y
vers4.1 = y
vers4.2 = y
udp = n
tcp = y

[mountd]
manage-gids = y
EOF
    
    log_info "NFS server settings configured"
}

# Start NFS services
start_nfs() {
    log_info "Starting NFS services..."
    
    # Export all filesystems
    log_info "Exporting filesystems..."
    exportfs -ra || die "Failed to export filesystems"
    
    # Enable and start NFS server
    enable_and_start_service nfs-server
    
    # Start additional services
    systemctl start rpcbind 2>/dev/null || true
    systemctl enable rpcbind 2>/dev/null || true
    
    log_info "NFS services started successfully"
    
    # Show active exports
    log_info "Active NFS exports:"
    exportfs -v | while read -r line; do
        log_info "  $line"
    done
}

# =============================================================================
# STATUS AND VERIFICATION
# =============================================================================

# Show service status
show_service_status() {
    log_info "Service Status:"
    log_info "----------------------------------------"
    
    # Samba status
    log_info "Samba:"
    if service_active smbd; then
        log_info "  smbd: Active"
    else
        log_info "  smbd: Inactive"
    fi
    
    if service_active nmbd; then
        log_info "  nmbd: Active"
    else
        log_info "  nmbd: Inactive"
    fi
    
    # NFS status
    log_info ""
    log_info "NFS:"
    if service_active nfs-server; then
        log_info "  nfs-server: Active"
    else
        log_info "  nfs-server: Inactive"
    fi
    
    log_info "----------------------------------------"
}

# Test shares
test_shares() {
    local share_path="${SAMBA_SHARE_PATH:-${ISCSI_MOUNT_POINT}}"
    
    log_info "Testing shares..."
    
    # Test Samba
    log_info "Samba shares:"
    smbclient -L localhost -N 2>/dev/null | grep -A 10 "Sharename" | while read -r line; do
        log_info "  $line"
    done
    
    # Test NFS
    log_info ""
    log_info "NFS exports:"
    showmount -e localhost 2>/dev/null | while read -r line; do
        log_info "  $line"
    done
}

# =============================================================================
# MAIN EXECUTION
# =============================================================================

main() {
    log_info "Starting Samba and NFS setup..."
    
    # Acquire lock
    acquire_lock
    
    # Install and configure Samba
    install_samba
    configure_samba
    start_samba
    
    # Install and configure NFS
    install_nfs
    configure_nfs
    configure_nfs_server
    start_nfs
    
    # Show status
    show_service_status
    
    # Test shares
    test_shares
    
    log_info "Samba and NFS setup completed successfully"
    log_info ""
    log_info "Access information:"
    log_info "  Samba: \\\\$(hostname)\\${SAMBA_SHARE_NAME:-iscsi-storage}"
    log_info "  NFS: $(hostname):${NFS_EXPORT_PATH:-${ISCSI_MOUNT_POINT}}"
    
    return 0
}

# Run main function
main "$@"
